### ISSUE TITLE
Clean up packaging of GStreamer SDK

### ISSUE THREAD

**Issue by bgilbert** [cmusatyalab/vmnetx-android#26]
Cerbero [now has a `bundle-source` command](https://bugzilla.gnome.org/show_bug.cgi?id=742830#c13).  If the GStreamer 1.6 SDK binaries are shipped alongside a source tarball, ship those and stop building the SDK ourselves.  If not, switch to using `bundle-source` rather than tarring up the Cerbero build tree.

**Comment by bgilbert** [comment]
GStreamer [now ships SDK source tarballs](http://gstreamer.freedesktop.org/data/pkg/src/).

**Comment by jaharkes** [comment]
vmnetx 0.2.1 sources now include the gstreamer sdk source tarball instead of building our own
